<?php

use Illuminate\Database\Seeder;

class DataRowsTableSeeder extends Seeder {

    private $data = [
        array(
            'data_type_id' => 'users',
            'field' => 'id',
            'type' => 'number',
            'display_name' => 'ID',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'email',
            'type' => 'text',
            'display_name' => 'Email',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'password',
            'type' => 'password',
            'display_name' => 'Password',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'remember_token',
            'type' => 'text',
            'display_name' => 'Remember Token',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'avatar',
            'type' => 'image',
            'display_name' => 'Avatar',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 10,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'user_belongsto_role_relationship',
            'type' => 'relationship',
            'display_name' => 'Role',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"model":"App\\\\Models\\\\Role","table":"roles","type":"belongsTo","column":"role_id","key":"id","label":"display_name","pivot_table":"roles","pivot":"0","taggable":"0"}',
            'order' => 13,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'user_belongstomany_role_relationship',
            'type' => 'relationship',
            'display_name' => 'Roles',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"model":"App\\\\Models\\\\Role","table":"roles","type":"belongsToMany","column":"id","key":"id","label":"display_name","pivot_table":"user_roles","pivot":"1","taggable":"0"}',
            'order' => 15,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'settings',
            'type' => 'hidden',
            'display_name' => 'Settings',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 16,
        ),
        array(
            'data_type_id' => 'menus',
            'field' => 'id',
            'type' => 'number',
            'display_name' => 'ID',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => NULL,
            'order' => 1,
        ),
        array(
            'data_type_id' => 'menus',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => NULL,
            'order' => 2,
        ),
        array(
            'data_type_id' => 'menus',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => NULL,
            'order' => 3,
        ),
        array(
            'data_type_id' => 'menus',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => NULL,
            'order' => 4,
        ),
        array(
            'data_type_id' => 'roles',
            'field' => 'id',
            'type' => 'number',
            'display_name' => 'ID',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => NULL,
            'order' => 1,
        ),
        array(
            'data_type_id' => 'roles',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => NULL,
            'order' => 2,
        ),
        array(
            'data_type_id' => 'roles',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => NULL,
            'order' => 3,
        ),
        array(
            'data_type_id' => 'roles',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => NULL,
            'order' => 4,
        ),
        array(
            'data_type_id' => 'roles',
            'field' => 'display_name',
            'type' => 'text',
            'display_name' => 'Display Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => NULL,
            'order' => 5,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'role_id',
            'type' => 'text',
            'display_name' => 'Role',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 12,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'description',
            'type' => 'rich_text_box',
            'display_name' => 'Description',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:1000"}}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'parent_category_id',
            'type' => 'text',
            'display_name' => 'Parent Category Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'category_hasmany_category_relationship',
            'type' => 'relationship',
            'display_name' => 'Parent Categories',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Category","table":"category","type":"belongsTo","column":"parent_category_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"on"}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'purchase_price',
            'type' => 'number',
            'display_name' => 'Purchase Price',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"numeric|min:0|max:999.999.999,999"},"default":"0"}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'sale_price',
            'type' => 'number',
            'display_name' => 'Sale Price',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"numeric|min:0|max:999.999.999,999"},"default":"0"}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'amount',
            'type' => 'number',
            'display_name' => 'Amount',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"integer|min:0|max:999.999.999"},"default":"0"}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 10,
        ),
        array(
            'data_type_id' => 'category',
            'field' => 'category_belongstomany_product_relationship',
            'type' => 'relationship',
            'display_name' => 'Products',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Product","table":"product","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"product_category","pivot":"1","taggable":"0"}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'description',
            'type' => 'rich_text_box',
            'display_name' => 'Description',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"max:1000"}}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'product',
            'field' => 'product_belongstomany_category_relationship',
            'type' => 'relationship',
            'display_name' => 'category',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Category","table":"category","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"product_category","pivot":"1","taggable":"on"}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'extra',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'extra',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'extra',
            'field' => 'description',
            'type' => 'text_area',
            'display_name' => 'Description',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:1000"}}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'extra',
            'field' => 'percentage',
            'type' => 'number',
            'display_name' => 'Percentage',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"required|numeric|min:0|max:100"}}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'extra',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'extra',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'extra',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Refund number',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'reason',
            'type' => 'text',
            'display_name' => 'Reason',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:5|max:250"}}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'description',
            'type' => 'rich_text_box',
            'display_name' => 'Description',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:1000"}}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'amount',
            'type' => 'text',
            'display_name' => 'Amount',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:1|max:9999"}}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'date',
            'type' => 'text',
            'display_name' => 'Date',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"before_or_equal:2019-01-01"}}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'detail_id',
            'type' => 'text',
            'display_name' => 'Detail Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'refund',
            'field' => 'refund_belongsto_detail_relationship',
            'type' => 'relationship',
            'display_name' => 'Detail',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Detail","table":"detail","type":"belongsTo","column":"detail_id","key":"id","label":"product_id","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 10,
        ),
        array(
            'data_type_id' => 'payment_method',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'payment_method',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'payment_method',
            'field' => 'description',
            'type' => 'text',
            'display_name' => 'Description',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:1000"}}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'payment_method',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'payment_method',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'payment_method',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'identification',
            'type' => 'text',
            'display_name' => 'Identification',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:50"}}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'identification_type',
            'type' => 'select_dropdown',
            'display_name' => 'Identification Type',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"default":"unknown","options":{"unknown":"unknown","passport":"passport","officialidentification":"official identification","other":"other"},"validation":{"rule":"max:50"}}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'photo',
            'type' => 'image',
            'display_name' => 'Photo',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"quality":"70%"}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'First Name',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'middle_name',
            'type' => 'text',
            'display_name' => 'Middle Name',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'first_surname',
            'type' => 'text',
            'display_name' => 'First Surname',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'second_surname',
            'type' => 'text',
            'display_name' => 'Second Surname',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:250"}}',
            'order' => 10,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'blood_group_rh',
            'type' => 'select_dropdown',
            'display_name' => 'Blood Group and Rh',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"default":"unknown","options":{"unknown":"unknown","A+":"A+","A-":"A-","B+":"B+","B-":"B-","AB+":"AB+","AB-":"AB-","O+":"O+","O-":"O-"},"validation":{"rule":"max:3"}}',
            'order' => 11,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'city_birth_id',
            'type' => 'text',
            'display_name' => 'City Birth Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'birthdate',
            'type' => 'date',
            'display_name' => 'Birthdate',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"after_or_equal:01-01-1900"}}',
            'order' => 12,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'address',
            'type' => 'text',
            'display_name' => 'Address',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:250"}}',
            'order' => 14,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'email',
            'type' => 'text',
            'display_name' => 'Contact Email',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"email|max:250"}}',
            'order' => 15,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'phone',
            'type' => 'text',
            'display_name' => 'Phone',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"max:250"}}',
            'order' => 16,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'gender',
            'type' => 'select_dropdown',
            'display_name' => 'Gender',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"default":"unknown","options":{"unknown":"unknown","Female":"Female","Male":"Male"},"description":"We require this field because one of the many ways we use this information is in communicationg with the client insurance company. Please make sure you provide here is the same as what you insurance provider has on file."}',
            'order' => 17,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 18,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 19,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 20,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'person_hasone_user_relationship',
            'type' => 'relationship',
            'display_name' => 'Account Email',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{"model":"App\\\\User","table":"users","type":"hasOne","column":"person_id","key":"id","label":"email","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 21,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'person_hasone_invoice_relationship',
            'type' => 'relationship',
            'display_name' => 'Invoice numbers',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Invoice","table":"invoice","type":"hasOne","column":"client_person_id","key":"id","label":"id","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 22,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'person_belongsto_city_relationship',
            'type' => 'relationship',
            'display_name' => 'City of birth',
            'required' => 0,
            'browse' => 0,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\City","table":"city","type":"belongsTo","column":"city_birth_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 13,
        ),
        array(
            'data_type_id' => 'state',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'state',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'state',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'state',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'state',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'state',
            'field' => 'state_hasone_city_relationship',
            'type' => 'relationship',
            'display_name' => 'city',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\City","table":"city","type":"hasOne","column":"state_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'city',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'city',
            'field' => 'name',
            'type' => 'text',
            'display_name' => 'Name',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"required|min:2|max:250"}}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'city',
            'field' => 'state_id',
            'type' => 'text',
            'display_name' => 'State Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'city',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'city',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'city',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'city',
            'field' => 'city_belongsto_state_relationship',
            'type' => 'relationship',
            'display_name' => 'state',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\State","table":"state","type":"belongsTo","column":"state_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Invoice number',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'client_person_id',
            'type' => 'text',
            'display_name' => 'Client Person Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'seller_user_id',
            'type' => 'text',
            'display_name' => 'Seller User Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'payment_method_id',
            'type' => 'text',
            'display_name' => 'Payment Method Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'status',
            'type' => 'checkbox',
            'display_name' => 'Status',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"on":"Paid","off":"Not paid","checked":true,"validation":{"rule":"max:50"}}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'total',
            'type' => 'text',
            'display_name' => 'Total',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{"disable":"disable"}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'invoice_belongsto_person_relationship',
            'type' => 'relationship',
            'display_name' => 'Client ID',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Person","table":"person","type":"belongsTo","column":"client_person_id","key":"id","label":"identification","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 12,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'invoice_belongsto_user_relationship',
            'type' => 'relationship',
            'display_name' => 'Seller',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"model":"App\\\\User","table":"users","type":"belongsTo","column":"seller_user_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 13,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'invoice_hasmany_detail_relationship',
            'type' => 'relationship',
            'display_name' => 'Products',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{"model":"App\\\\Models\\\\Product","table":"product","type":"belongsToMany","column":"id","key":"id","label":"name","pivot_table":"detail","pivot":"1","taggable":"on"}',
            'order' => 11,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'user_belongsto_person_relationship',
            'type' => 'relationship',
            'display_name' => 'Identification',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Person","table":"person","type":"belongsTo","column":"person_id","key":"id","label":"identification","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 11,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'email_verified_at',
            'type' => 'timestamp',
            'display_name' => 'Email Verified At',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 14,
        ),
        array(
            'data_type_id' => 'users',
            'field' => 'person_id',
            'type' => 'text',
            'display_name' => 'Person Id',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'id',
            'type' => 'number',
            'display_name' => 'Detail number',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'extra_id',
            'type' => 'number',
            'display_name' => 'Extra Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'product_id',
            'type' => 'text',
            'display_name' => 'Product Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'invoice_id',
            'type' => 'text',
            'display_name' => 'Invoice Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'amount',
            'type' => 'number',
            'display_name' => 'Amount',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"required|numeric|min:1"}}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 10,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 11,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'detail_belongsto_invoice_relationship',
            'type' => 'relationship',
            'display_name' => 'Invoice Number',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Invoice","table":"invoice","type":"belongsTo","column":"invoice_id","key":"id","label":"id","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'detail_belongsto_product_relationship',
            'type' => 'relationship',
            'display_name' => 'Product',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Product","table":"product","type":"belongsTo","column":"product_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'detail',
            'field' => 'detail_belongsto_extra_relationship',
            'type' => 'relationship',
            'display_name' => 'Discount or Surcharge',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Extra","table":"extra","type":"belongsTo","column":"extra_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'invoice_belongsto_payment_method_relationship',
            'type' => 'relationship',
            'display_name' => 'Payment Method',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\PaymentMethod","table":"payment_method","type":"belongsTo","column":"payment_method_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 10,
        ),
        array(
            'data_type_id' => 'person',
            'field' => 'status',
            'type' => 'select_dropdown',
            'display_name' => 'Status',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"default":"Active","options":{"Active":"Active","Inactive":"Inactive"}}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'id',
            'type' => 'text',
            'display_name' => 'Id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'person_id',
            'type' => 'text',
            'display_name' => 'Person Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'invoice_id',
            'type' => 'text',
            'display_name' => 'Invoice Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'extra_id',
            'type' => 'text',
            'display_name' => 'Extra Id',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'month',
            'type' => 'date',
            'display_name' => 'Month',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"after_or_equal:01-01-2019"}}',
            'order' => 7,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'deleted_at',
            'type' => 'timestamp',
            'display_name' => 'Deleted At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 10,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 11,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 12,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'membership_belongsto_person_relationship',
            'type' => 'relationship',
            'display_name' => 'Person ID',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Person","table":"person","type":"belongsTo","column":"person_id","key":"id","label":"identification","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'invoice',
            'field' => 'invoice_hasone_membership_relationship',
            'type' => 'relationship',
            'display_name' => 'membership',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{"model":"App\\\\Models\\\\Membership","table":"membership","type":"hasOne","column":"invoice_id","key":"id","label":"month","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 14,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'price',
            'type' => 'number',
            'display_name' => 'Price',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 0,
            'details' => '{"validation":{"rule":"numeric|min:0|max:999.999.999,999"},"default":"0"}',
            'order' => 8,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'membership_belongsto_invoice_relationship',
            'type' => 'relationship',
            'display_name' => 'Invoice number',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Invoice","table":"invoice","type":"belongsTo","column":"invoice_id","key":"id","label":"id","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'membership_belongsto_extra_relationship',
            'type' => 'relationship',
            'display_name' => 'Discount',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Extra","table":"extra","type":"belongsTo","column":"extra_id","key":"id","label":"name","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 9,
        ),
        array(
            'data_type_id' => 'membership',
            'field' => 'person_hasone_membership_relationship',
            'type' => 'relationship',
            'display_name' => 'Memberships',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{"model":"App\\\\Models\\\\Membership","table":"membership","type":"hasOne","column":"person_id","key":"id","label":"month","pivot_table":"category","pivot":"0","taggable":"0"}',
            'order' => 24,
        ),
        array(
            'data_type_id' => 'attendances',
            'field' => 'id',
            'type' => 'hidden',
            'display_name' => 'id',
            'required' => 1,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 1,
        ),
        array(
            'data_type_id' => 'attendances',
            'field' => 'attendance_belongsto_user_relationship',
            'type' => 'relationship',
            'display_name' => 'users',
            'required' => 0,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"model":"App\\\\Models\\\\Person","table":"users","type":"belongsTo","column":"id","key":"id","label":"name","pivot_table":"attendances","pivot":"0","taggable":"0"}',
            'order' => 2,
        ),
        array(
            'data_type_id' => 'attendances',
            'field' => 'date',
            'type' => 'date',
            'display_name' => 'Date',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"validation":{"rule":"before:tomorrow","messages":{"required":"Date Should be Before Tomorrow."}}}',
            'order' => 5,
        ),
        array(
            'data_type_id' => 'attendances',
            'field' => 'mark_attendance',
            'type' => 'checkbox',
            'display_name' => 'Mark Attendance',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{"on":"Present","off":"Absent","checked":false}',
            'order' => 4,
        ),
        array(
            'data_type_id' => 'attendances',
            'field' => 'user_id',
            'type' => 'text',
            'display_name' => 'User Id',
            'required' => 1,
            'browse' => 1,
            'read' => 1,
            'edit' => 1,
            'add' => 1,
            'delete' => 1,
            'details' => '{}',
            'order' => 3,
        ),
        array(
            'data_type_id' => 'attendances',
            'field' => 'created_at',
            'type' => 'timestamp',
            'display_name' => 'Created At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 6,
        ),
        array(
            'data_type_id' => 'attendances',
            'field' => 'updated_at',
            'type' => 'timestamp',
            'display_name' => 'Updated At',
            'required' => 0,
            'browse' => 0,
            'read' => 0,
            'edit' => 0,
            'add' => 0,
            'delete' => 0,
            'details' => '{}',
            'order' => 7,
        ),
    ];

    public function run() {
        foreach ($this->data as $each) {
            $obj = \TCG\Voyager\Models\DataType::where('name', $each['data_type_id'])->first();

            if (!$obj) {
                continue;
            }
            $each['data_type_id'] = $obj->id;

            $each['details'] = json_decode($each['details']);

            \TCG\Voyager\Models\DataRow::create($each);
        }
    }
}