<?php

use Illuminate\Database\Seeder;

class MenuItemsTableSeeder extends Seeder {

    private $data = [
        array(
            'menu_id' => 'admin',
            'title' => 'Dashboard',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-boat',
            'color' => NULL,
            'parent_id' => NULL,
            'order' => 1,
            'route' => 'voyager.dashboard',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Tools',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-tools',
            'color' => NULL,
            'parent_id' => NULL,
            'order' => 11,
            'route' => NULL,
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Settings',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-settings',
            'color' => NULL,
            'parent_id' => NULL,
            'order' => 9,
            'route' => 'voyager.settings.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Admin',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-user-lock',
            'color' => '#000000',
            'parent_id' => NULL,
            'order' => 10,
            'route' => NULL,
            'parameters' => '',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Products',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-gifts',
            'color' => '#000000',
            'parent_id' => NULL,
            'order' => 5,
            'route' => NULL,
            'parameters' => '',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Sells',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-hand-holding-usd',
            'color' => '#000000',
            'parent_id' => NULL,
            'order' => 4,
            'route' => NULL,
            'parameters' => '',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Memberships',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-dumbbell',
            'color' => '#000000',
            'parent_id' => NULL,
            'order' => 3,
            'route' => 'voyager.membership.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'People',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-users',
            'color' => '#000000',
            'parent_id' => NULL,
            'order' => 2,
            'route' => 'voyager.people.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Country',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-globe-americas',
            'color' => '#000000',
            'parent_id' => NULL,
            'order' => 6,
            'route' => NULL,
            'parameters' => '',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Menu Builder',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-list',
            'color' => NULL,
            'parent_id' => 5,
            'order' => 1,
            'route' => 'voyager.menus.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Database',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-data',
            'color' => NULL,
            'parent_id' => 5,
            'order' => 2,
            'route' => 'voyager.database.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Compass',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-compass',
            'color' => NULL,
            'parent_id' => 5,
            'order' => 3,
            'route' => 'voyager.compass.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'BREAD',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-bread',
            'color' => NULL,
            'parent_id' => 5,
            'order' => 4,
            'route' => 'voyager.bread.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Media',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-images',
            'color' => NULL,
            'parent_id' => 11,
            'order' => 3,
            'route' => 'voyager.media.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Users',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-person',
            'color' => NULL,
            'parent_id' => 11,
            'order' => 2,
            'route' => 'voyager.users.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Roles',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-lock',
            'color' => NULL,
            'parent_id' => 11,
            'order' => 1,
            'route' => 'voyager.roles.index',
            'parameters' => NULL,
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Categories',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'voyager-categories',
            'color' => '#000000',
            'parent_id' => 12,
            'order' => 2,
            'route' => 'voyager.category.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Products',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-gift',
            'color' => '#000000',
            'parent_id' => 12,
            'order' => 1,
            'route' => 'voyager.product.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Invoices',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-print',
            'color' => '#000000',
            'parent_id' => 15,
            'order' => 1,
            'route' => 'voyager.invoice.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Discounts',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-percent',
            'color' => '#000000',
            'parent_id' => 15,
            'order' => 3,
            'route' => 'voyager.extra.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Refund',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-undo-alt',
            'color' => '#000000',
            'parent_id' => 15,
            'order' => 4,
            'route' => 'voyager.refund.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Payment methods',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-credit-card',
            'color' => '#000000',
            'parent_id' => 15,
            'order' => 5,
            'route' => 'voyager.payment-method.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Details',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-file-invoice',
            'color' => '#000000',
            'parent_id' => 15,
            'order' => 2,
            'route' => 'voyager.detail.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'States',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-map-marked-alt',
            'color' => '#000000',
            'parent_id' => 23,
            'order' => 2,
            'route' => 'voyager.state.index',
            'parameters' => 'null',
        ),
        array(
            'menu_id' => 'admin',
            'title' => 'Cities',
            'url' => '',
            'target' => '_self',
            'icon_class' => 'fas fa-city',
            'color' => '#000000',
            'parent_id' => 23,
            'order' => 1,
            'route' => 'voyager.city.index',
            'parameters' => NULL,
        ),

    ];

    public function run() {
        foreach ($this->data as $each) {
            $obj = \TCG\Voyager\Models\Menu::where('name', $each['menu_id'])->first();

            if (!$obj) {
                continue;
            }
            $each['menu_id'] = $obj->id;

            \TCG\Voyager\Models\MenuItem::create($each);
        }

    }
}