<?php

use Illuminate\Database\Seeder;

class SettingsTableSeeder extends Seeder {

    private $data = [
        array(
            'key' => 'admin.bg_image',
            'display_name' => 'Admin Background Image',
            'value' => 'settings\\July2019\\g2b3XERL0W0tAF3s892B.jpg',
            'details' => '',
            'type' => 'image',
            'order' => 5,
            'group' => 'Admin',
        ),
        array(
            'key' => 'admin.title',
            'display_name' => 'Admin Title',
            'value' => 'Motion Gym Panel',
            'details' => '',
            'type' => 'text',
            'order' => 1,
            'group' => 'Admin',
        ),
        array(
            'key' => 'admin.description',
            'display_name' => 'Admin Description',
            'value' => 'Welcome to your Admin. Panel.',
            'details' => '',
            'type' => 'text',
            'order' => 2,
            'group' => 'Admin',
        ),
        array(
            'key' => 'admin.loader',
            'display_name' => 'Admin Loader',
            'value' => 'settings\\July2019\\aZQ8rjcsvrUSwzSJhJaC.gif',
            'details' => '',
            'type' => 'image',
            'order' => 3,
            'group' => 'Admin',
        ),
        array(
            'key' => 'admin.icon_image',
            'display_name' => 'Admin Icon Image',
            'value' => 'settings\\July2019\\Aoqdp90iNVqWNC1Dk0NR.png',
            'details' => '',
            'type' => 'image',
            'order' => 4,
            'group' => 'Admin',
        ),
        array(
            'key' => 'company.address',
            'display_name' => 'Address',
            'value' => NULL,
            'details' => NULL,
            'type' => 'text',
            'order' => 7,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.phone_primary',
            'display_name' => 'Phone Primary',
            'value' => NULL,
            'details' => NULL,
            'type' => 'text_area',
            'order' => 8,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.phone_secondary',
            'display_name' => 'Phone Secondary',
            'value' => NULL,
            'details' => NULL,
            'type' => 'text_area',
            'order' => 9,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.email_contact',
            'display_name' => 'Contact Email',
            'value' => NULL,
            'details' => NULL,
            'type' => 'text_area',
            'order' => 10,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.history',
            'display_name' => 'History of the company',
            'value' => NULL,
            'details' => NULL,
            'type' => 'rich_text_box',
            'order' => 11,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.vision',
            'display_name' => 'Company vision',
            'value' => NULL,
            'details' => NULL,
            'type' => 'rich_text_box',
            'order' => 12,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.mision',
            'display_name' => 'Company mision',
            'value' => NULL,
            'details' => NULL,
            'type' => 'rich_text_box',
            'order' => 18,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.conditions',
            'display_name' => 'Conditions of service',
            'value' => NULL,
            'details' => NULL,
            'type' => 'rich_text_box',
            'order' => 19,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.policy',
            'display_name' => 'Privacy policy',
            'value' => NULL,
            'details' => NULL,
            'type' => 'rich_text_box',
            'order' => 22,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.facebook',
            'display_name' => 'Facebook URL',
            'value' => 'https://www.facebook.com/',
            'details' => NULL,
            'type' => 'text',
            'order' => 23,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.twitter',
            'display_name' => 'Twitter URL',
            'value' => 'https://www.twitter.com/',
            'details' => NULL,
            'type' => 'text',
            'order' => 24,
            'group' => 'Company',
        ),
        array(
            'key' => 'company.slogan',
            'display_name' => 'Slogan',
            'value' => 'Are you ready to get fit?',
            'details' => NULL,
            'type' => 'text',
            'order' => 6,
            'group' => 'Company',
        ),
    ];

    public function run() {
        foreach ($this->data as $each) {
            \TCG\Voyager\Models\Setting::create($each);
        }
    }
}